# Generated by Django 4.2.8 on 2025-12-10 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('arxiv_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('semantic_scholar_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('has_pdf', models.BooleanField(default=False)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_text', models.TextField(blank=True, null=True)),
                ('abstract_summary_short', models.TextField(blank=True, null=True)),
                ('abstract_summary_medium', models.TextField(blank=True, null=True)),
                ('abstract_summary_long', models.TextField(blank=True, null=True)),
                ('pdf_summary_short', models.TextField(blank=True, null=True)),
                ('pdf_summary_medium', models.TextField(blank=True, null=True)),
                ('pdf_summary_long', models.TextField(blank=True, null=True)),
                ('key_findings', models.TextField(blank=True, null=True)),
                ('methodology_gaps', models.TextField(blank=True, null=True)),
                ('knowledge_gaps', models.TextField(blank=True, null=True)),
                ('future_directions', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('summary_level', models.CharField(blank=True, max_length=20, null=True)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('open_access_only', models.BooleanField(default=False)),
                ('databases', models.JSONField(blank=True, default=list)),
                ('results_count', models.IntegerField(blank=True, null=True)),
                ('papers_found', models.JSONField(blank=True, default=list)),
                ('search_duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='api.project')),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('note_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.project')),
            ],
            options={
                'db_table': 'project_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('papers_included', models.JSONField(blank=True, default=list)),
                ('review_type', models.CharField(blank=True, max_length=50, null=True)),
                ('detail_level', models.CharField(blank=True, max_length=20, null=True)),
                ('markdown_content', models.TextField(blank=True, null=True)),
                ('latex_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_reviews', to='api.project')),
            ],
            options={
                'db_table': 'literature_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('importance', models.IntegerField(default=3)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_papers', to='api.paper')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_papers', to='api.project')),
            ],
            options={
                'db_table': 'project_papers',
                'unique_together': {('project', 'paper')},
            },
        ),
    ]
